### ISSUE TITLE
Cannot successfully launch app

### ISSUE THREAD

**Issue by GarfieldsPipe** [dangeru/awoo#45]
```

May 07 19:53:08 localhost.server.com systemd[1]: Started awoo.
May 07 19:53:08 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/rerun/options.rb:6: warning: assigned but unused variable - libdir
May 07 19:53:08 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/rerun/watcher.rb:104: warning: assigned but unused variable - e
May 07 19:53:08 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/rerun/runner.rb:307: warning: assigned but unused variable - e
May 07 19:53:08 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/rerun/runner.rb:141: warning: instance variable @already_running not initialized
May 07 19:53:08 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/rerun/runner.rb:159: warning: instance variable @keypress_thread not initialized
May 07 19:53:08 localhost.server.com env[4885]: 19:53:08 [rerun] Src launched
May 07 19:53:08 localhost.server.com env[4885]: /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:368: warning: shadowing outer local variable - filename
May 07 19:53:08 localhost.server.com env[4885]: /opt/awoo/src/routes/utils/search.rb:38: warning: shadowing outer local variable - where_clause
May 07 19:53:08 localhost.server.com env[4885]: /var/lib/gems/2.5.0/gems/mini_magick-4.11.0/lib/mini_magick/tool.rb:199: warning: shadowing outer local variable - value
May 07 19:53:08 localhost.server.com env[4885]: /var/lib/gems/2.5.0/gems/mini_magick-4.11.0/lib/mini_magick/image/info.rb:70: warning: ambiguous first argument; put parentheses or a s
May 07 19:53:08 localhost.server.com env[4885]: /opt/awoo/src/routes/utils/captcha.rb:3: warning: setting Encoding.default_internal
May 07 19:53:08 localhost.server.com env[4885]: /opt/awoo/src/routes/utils/captcha.rb:4: warning: setting Encoding.default_external
May 07 19:53:08 localhost.server.com env[4885]: /opt/awoo/src/app.rb:21:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1537:in `new'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1527:in `prototype'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1573:in `start_server'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1509:in `run!'
May 07 19:53:08 localhost.server.com env[4885]:         from /opt/awoo/src/config.ru:10:in `block in <main>'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
May 07 19:53:08 localhost.server.com env[4885]:         from /var/lib/gems/2.5.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
May 07 19:53:08 localhost.server.com env[4885]:         from /usr/local/bin/rackup:23:in `load'
May 07 19:53:08 localhost.server.com env[4885]:         from /usr/local/bin/rackup:23:in `<main>'
May 07 19:53:08 localhost.server.com env[4885]: Loading board test...
May 07 19:53:08 localhost.server.com env[4885]: Loading board burg...
May 07 19:53:08 localhost.server.com env[4885]: Loading board staff...
May 07 19:53:08 localhost.server.com env[4885]: Loading board all...
May 07 19:53:08 localhost.server.com env[4885]: All threads pruned
May 07 19:53:08 localhost.server.com env[4885]: Updating legacy burgs
May 07 19:53:08 localhost.server.com env[4885]: All legacy burgs updated
May 07 19:53:08 localhost.server.com env[4885]: Updating legacy archived threads
May 07 19:53:08 localhost.server.com env[4885]: All legacy archived threads updated
May 07 19:53:08 localhost.server.com env[4885]: Awoo is starting...
May 07 19:53:10 localhost.server.com env[4885]: 19:53:08 [rerun] Rerun (4885) running Src (4891)
May 07 19:53:10 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/rerun/runner.rb:200: warning: instance variable @watcher not initialized
May 07 19:53:10 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/rerun/watcher.rb:51: warning: FileTest.exists? is a deprecated name, use FileTest.exist? instead
May 07 19:53:10 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/rerun/watcher.rb:75: warning: instance variable @listener not initialized
May 07 19:53:10 localhost.server.com env[4885]: /usr/lib/ruby/vendor_ruby/ffi/library.rb:333: warning: assigned but unused variable - s

```

**Comment by naomiEve** [comment]
try running with sinatra 2.0 and not 2.2
